spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiwx?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=CST&useSSL=false
    username: aiwx
    password: aiwxaiwxaiwx

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

xyz:
  whllhw:
    weixin:
      appid:
      secret:

logging:
  level:
    - root: warn

    - xyz:
        whllhw:
          mapper: trace
mybatis:
  config-location: classpath:mybatis.xml

